//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace UclOpenHfVisualDataSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Block
    {
    
        private System.Collections.Generic.List<Trial> _availableTrials;
    
        private bool _randomiseTrialOrder;
    
        private int _maxTrials;
    
        public Block()
        {
            _availableTrials = new System.Collections.Generic.List<Trial>();
            _randomiseTrialOrder = false;
            _maxTrials = 10;
        }
    
        protected Block(Block other)
        {
            _availableTrials = other._availableTrials;
            _randomiseTrialOrder = other._randomiseTrialOrder;
            _maxTrials = other._maxTrials;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("availableTrials", Required=Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.List<Trial> AvailableTrials
        {
            get
            {
                return _availableTrials;
            }
            set
            {
                _availableTrials = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("randomiseTrialOrder")]
        public bool RandomiseTrialOrder
        {
            get
            {
                return _randomiseTrialOrder;
            }
            set
            {
                _randomiseTrialOrder = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("maxTrials")]
        public int MaxTrials
        {
            get
            {
                return _maxTrials;
            }
            set
            {
                _maxTrials = value;
            }
        }
    
        public System.IObservable<Block> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Block(this)));
        }
    
        public System.IObservable<Block> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Block(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("AvailableTrials = " + _availableTrials + ", ");
            stringBuilder.Append("RandomiseTrialOrder = " + _randomiseTrialOrder + ", ");
            stringBuilder.Append("MaxTrials = " + _maxTrials);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayCalibration
    {
    
        private DisplayIntrinsics _intrinsics;
    
        private DisplayExtrinsics _extrinsics;
    
        public DisplayCalibration()
        {
            _intrinsics = new DisplayIntrinsics();
            _extrinsics = new DisplayExtrinsics();
        }
    
        protected DisplayCalibration(DisplayCalibration other)
        {
            _intrinsics = other._intrinsics;
            _extrinsics = other._extrinsics;
        }
    
        /// <summary>
        /// Intrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("intrinsics")]
        [System.ComponentModel.DescriptionAttribute("Intrinsics")]
        public DisplayIntrinsics Intrinsics
        {
            get
            {
                return _intrinsics;
            }
            set
            {
                _intrinsics = value;
            }
        }
    
        /// <summary>
        /// Extrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("extrinsics")]
        [System.ComponentModel.DescriptionAttribute("Extrinsics")]
        public DisplayExtrinsics Extrinsics
        {
            get
            {
                return _extrinsics;
            }
            set
            {
                _extrinsics = value;
            }
        }
    
        public System.IObservable<DisplayCalibration> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayCalibration(this)));
        }
    
        public System.IObservable<DisplayCalibration> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayCalibration(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Intrinsics = " + _intrinsics + ", ");
            stringBuilder.Append("Extrinsics = " + _extrinsics);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayExtrinsics
    {
    
        private Vector3 _rotation;
    
        private Vector3 _translation;
    
        public DisplayExtrinsics()
        {
            _rotation = new Vector3();
            _translation = new Vector3();
        }
    
        protected DisplayExtrinsics(DisplayExtrinsics other)
        {
            _rotation = other._rotation;
            _translation = other._translation;
        }
    
        /// <summary>
        /// Rotation vector (radians)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("rotation")]
        [System.ComponentModel.DescriptionAttribute("Rotation vector (radians)")]
        public Vector3 Rotation
        {
            get
            {
                return _rotation;
            }
            set
            {
                _rotation = value;
            }
        }
    
        /// <summary>
        /// Translation (in cm)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("translation")]
        [System.ComponentModel.DescriptionAttribute("Translation (in cm)")]
        public Vector3 Translation
        {
            get
            {
                return _translation;
            }
            set
            {
                _translation = value;
            }
        }
    
        public System.IObservable<DisplayExtrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayExtrinsics(this)));
        }
    
        public System.IObservable<DisplayExtrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayExtrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Rotation = " + _rotation + ", ");
            stringBuilder.Append("Translation = " + _translation);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayIntrinsics
    {
    
        private int _frameWidth;
    
        private int _frameHeight;
    
        private double _displayWidth;
    
        private double _displayHeight;
    
        public DisplayIntrinsics()
        {
            _frameWidth = 1920;
            _frameHeight = 1080;
            _displayWidth = 20D;
            _displayHeight = 15D;
        }
    
        protected DisplayIntrinsics(DisplayIntrinsics other)
        {
            _frameWidth = other._frameWidth;
            _frameHeight = other._frameHeight;
            _displayWidth = other._displayWidth;
            _displayHeight = other._displayHeight;
        }
    
        /// <summary>
        /// Frame width (px)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frameWidth")]
        [System.ComponentModel.DescriptionAttribute("Frame width (px)")]
        public int FrameWidth
        {
            get
            {
                return _frameWidth;
            }
            set
            {
                _frameWidth = value;
            }
        }
    
        /// <summary>
        /// Frame height (px)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frameHeight")]
        [System.ComponentModel.DescriptionAttribute("Frame height (px)")]
        public int FrameHeight
        {
            get
            {
                return _frameHeight;
            }
            set
            {
                _frameHeight = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayWidth")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayWidth
        {
            get
            {
                return _displayWidth;
            }
            set
            {
                _displayWidth = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayHeight")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayHeight
        {
            get
            {
                return _displayHeight;
            }
            set
            {
                _displayHeight = value;
            }
        }
    
        public System.IObservable<DisplayIntrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayIntrinsics(this)));
        }
    
        public System.IObservable<DisplayIntrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayIntrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("FrameWidth = " + _frameWidth + ", ");
            stringBuilder.Append("FrameHeight = " + _frameHeight + ", ");
            stringBuilder.Append("DisplayWidth = " + _displayWidth + ", ");
            stringBuilder.Append("DisplayHeight = " + _displayHeight);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Landmark
    {
    
        private double _size;
    
        private double _position;
    
        private double _centerOffset;
    
        private string _texture;
    
        private int _rewardValence;
    
        public Landmark()
        {
            _size = 1D;
            _position = 0D;
            _centerOffset = 0D;
            _rewardValence = 0;
        }
    
        protected Landmark(Landmark other)
        {
            _size = other._size;
            _position = other._position;
            _centerOffset = other._centerOffset;
            _texture = other._texture;
            _rewardValence = other._rewardValence;
        }
    
        /// <summary>
        /// This landmark's size in VR space.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("size")]
        [System.ComponentModel.DescriptionAttribute("This landmark\'s size in VR space.")]
        public double Size
        {
            get
            {
                return _size;
            }
            set
            {
                _size = value;
            }
        }
    
        /// <summary>
        /// This landmark's position in VR space.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("position")]
        [System.ComponentModel.DescriptionAttribute("This landmark\'s position in VR space.")]
        public double Position
        {
            get
            {
                return _position;
            }
            set
            {
                _position = value;
            }
        }
    
        /// <summary>
        /// Additonal offset to the corridor width used for layering landmark rendering. Higher values are further from the corridor midline.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("centerOffset")]
        [System.ComponentModel.DescriptionAttribute("Additonal offset to the corridor width used for layering landmark rendering. High" +
            "er values are further from the corridor midline.")]
        public double CenterOffset
        {
            get
            {
                return _centerOffset;
            }
            set
            {
                _centerOffset = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("texture", Required=Newtonsoft.Json.Required.Always)]
        public string Texture
        {
            get
            {
                return _texture;
            }
            set
            {
                _texture = value;
            }
        }
    
        /// <summary>
        /// Flag describing this landmark's reward valence.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rewardValence")]
        [System.ComponentModel.DescriptionAttribute("Flag describing this landmark\'s reward valence.")]
        public int RewardValence
        {
            get
            {
                return _rewardValence;
            }
            set
            {
                _rewardValence = value;
            }
        }
    
        public System.IObservable<Landmark> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Landmark(this)));
        }
    
        public System.IObservable<Landmark> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Landmark(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Size = " + _size + ", ");
            stringBuilder.Append("Position = " + _position + ", ");
            stringBuilder.Append("CenterOffset = " + _centerOffset + ", ");
            stringBuilder.Append("Texture = " + _texture + ", ");
            stringBuilder.Append("RewardValence = " + _rewardValence);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class MatrixArduino
    {
    
        private string _deviceType;
    
        private string _portName;
    
        private int _baudRate;
    
        private string _encoding;
    
        private string _newLine;
    
        private string _parity;
    
        private int _parityReplace;
    
        private int _dataBits;
    
        private string _stopBits;
    
        private string _handshake;
    
        private bool _discardNull;
    
        private bool _dtrEnable;
    
        private bool _rtsEnable;
    
        private int _readBufferSize;
    
        private int _writeBufferSize;
    
        private int _receivedBytesThreshold;
    
        private string _serialMessageSubjectName;
    
        public MatrixArduino()
        {
            _deviceType = "MatrixArduino";
            _baudRate = 9600;
            _newLine = "\r\n";
            _parity = "None";
            _parityReplace = 63;
            _dataBits = 8;
            _stopBits = "One";
            _handshake = "None";
            _discardNull = false;
            _dtrEnable = false;
            _rtsEnable = false;
            _readBufferSize = 4096;
            _writeBufferSize = 2048;
            _receivedBytesThreshold = 1;
            _serialMessageSubjectName = "SerialMessages";
        }
    
        protected MatrixArduino(MatrixArduino other)
        {
            _deviceType = other._deviceType;
            _portName = other._portName;
            _baudRate = other._baudRate;
            _encoding = other._encoding;
            _newLine = other._newLine;
            _parity = other._parity;
            _parityReplace = other._parityReplace;
            _dataBits = other._dataBits;
            _stopBits = other._stopBits;
            _handshake = other._handshake;
            _discardNull = other._discardNull;
            _dtrEnable = other._dtrEnable;
            _rtsEnable = other._rtsEnable;
            _readBufferSize = other._readBufferSize;
            _writeBufferSize = other._writeBufferSize;
            _receivedBytesThreshold = other._receivedBytesThreshold;
            _serialMessageSubjectName = other._serialMessageSubjectName;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("deviceType")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("portName", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Baud rate for serial communication.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("baudRate")]
        [System.ComponentModel.DescriptionAttribute("Baud rate for serial communication.")]
        public int BaudRate
        {
            get
            {
                return _baudRate;
            }
            set
            {
                _baudRate = value;
            }
        }
    
        /// <summary>
        /// Optional text encoding for interpreting incoming bytes.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("encoding")]
        [System.ComponentModel.DescriptionAttribute("Optional text encoding for interpreting incoming bytes.")]
        public string Encoding
        {
            get
            {
                return _encoding;
            }
            set
            {
                _encoding = value;
            }
        }
    
        /// <summary>
        /// Line termination sequence used to delimit incoming messages.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("newLine")]
        [System.ComponentModel.DescriptionAttribute("Line termination sequence used to delimit incoming messages.")]
        public string NewLine
        {
            get
            {
                return _newLine;
            }
            set
            {
                _newLine = value;
            }
        }
    
        /// <summary>
        /// Parity checking mode for the serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parity")]
        [System.ComponentModel.DescriptionAttribute("Parity checking mode for the serial port.")]
        public string Parity
        {
            get
            {
                return _parity;
            }
            set
            {
                _parity = value;
            }
        }
    
        /// <summary>
        /// Byte used to replace invalid bytes detected by a parity error.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parityReplace")]
        [System.ComponentModel.DescriptionAttribute("Byte used to replace invalid bytes detected by a parity error.")]
        public int ParityReplace
        {
            get
            {
                return _parityReplace;
            }
            set
            {
                _parityReplace = value;
            }
        }
    
        /// <summary>
        /// Number of data bits per serial frame.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dataBits")]
        [System.ComponentModel.DescriptionAttribute("Number of data bits per serial frame.")]
        public int DataBits
        {
            get
            {
                return _dataBits;
            }
            set
            {
                _dataBits = value;
            }
        }
    
        /// <summary>
        /// Number of stop bits per serial frame.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("stopBits")]
        [System.ComponentModel.DescriptionAttribute("Number of stop bits per serial frame.")]
        public string StopBits
        {
            get
            {
                return _stopBits;
            }
            set
            {
                _stopBits = value;
            }
        }
    
        /// <summary>
        /// Hardware or software handshaking mode.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("handshake")]
        [System.ComponentModel.DescriptionAttribute("Hardware or software handshaking mode.")]
        public string Handshake
        {
            get
            {
                return _handshake;
            }
            set
            {
                _handshake = value;
            }
        }
    
        /// <summary>
        /// Whether to discard null bytes appearing in the serial stream.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("discardNull")]
        [System.ComponentModel.DescriptionAttribute("Whether to discard null bytes appearing in the serial stream.")]
        public bool DiscardNull
        {
            get
            {
                return _discardNull;
            }
            set
            {
                _discardNull = value;
            }
        }
    
        /// <summary>
        /// Whether to enable Data Terminal Ready (DTR) control line.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dtrEnable")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable Data Terminal Ready (DTR) control line.")]
        public bool DtrEnable
        {
            get
            {
                return _dtrEnable;
            }
            set
            {
                _dtrEnable = value;
            }
        }
    
        /// <summary>
        /// Whether to enable Request To Send (RTS) control line.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rtsEnable")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable Request To Send (RTS) control line.")]
        public bool RtsEnable
        {
            get
            {
                return _rtsEnable;
            }
            set
            {
                _rtsEnable = value;
            }
        }
    
        /// <summary>
        /// Size, in bytes, of the read buffer.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("readBufferSize")]
        [System.ComponentModel.DescriptionAttribute("Size, in bytes, of the read buffer.")]
        public int ReadBufferSize
        {
            get
            {
                return _readBufferSize;
            }
            set
            {
                _readBufferSize = value;
            }
        }
    
        /// <summary>
        /// Size, in bytes, of the write buffer.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("writeBufferSize")]
        [System.ComponentModel.DescriptionAttribute("Size, in bytes, of the write buffer.")]
        public int WriteBufferSize
        {
            get
            {
                return _writeBufferSize;
            }
            set
            {
                _writeBufferSize = value;
            }
        }
    
        /// <summary>
        /// Minimum number of bytes in the buffer that triggers a read event.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("receivedBytesThreshold")]
        [System.ComponentModel.DescriptionAttribute("Minimum number of bytes in the buffer that triggers a read event.")]
        public int ReceivedBytesThreshold
        {
            get
            {
                return _receivedBytesThreshold;
            }
            set
            {
                _receivedBytesThreshold = value;
            }
        }
    
        /// <summary>
        /// Name of the subject to which parsed serial messages are published.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("serialMessageSubjectName")]
        [System.ComponentModel.DescriptionAttribute("Name of the subject to which parsed serial messages are published.")]
        public string SerialMessageSubjectName
        {
            get
            {
                return _serialMessageSubjectName;
            }
            set
            {
                _serialMessageSubjectName = value;
            }
        }
    
        public System.IObservable<MatrixArduino> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new MatrixArduino(this)));
        }
    
        public System.IObservable<MatrixArduino> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new MatrixArduino(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("BaudRate = " + _baudRate + ", ");
            stringBuilder.Append("Encoding = " + _encoding + ", ");
            stringBuilder.Append("NewLine = " + _newLine + ", ");
            stringBuilder.Append("Parity = " + _parity + ", ");
            stringBuilder.Append("ParityReplace = " + _parityReplace + ", ");
            stringBuilder.Append("DataBits = " + _dataBits + ", ");
            stringBuilder.Append("StopBits = " + _stopBits + ", ");
            stringBuilder.Append("Handshake = " + _handshake + ", ");
            stringBuilder.Append("DiscardNull = " + _discardNull + ", ");
            stringBuilder.Append("DtrEnable = " + _dtrEnable + ", ");
            stringBuilder.Append("RtsEnable = " + _rtsEnable + ", ");
            stringBuilder.Append("ReadBufferSize = " + _readBufferSize + ", ");
            stringBuilder.Append("WriteBufferSize = " + _writeBufferSize + ", ");
            stringBuilder.Append("ReceivedBytesThreshold = " + _receivedBytesThreshold + ", ");
            stringBuilder.Append("SerialMessageSubjectName = " + _serialMessageSubjectName);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class MatrixArduinoData
    {
    
        private int _encoderPos;
    
        private int _lastLeftLickTime;
    
        private int _lastRightLickTime;
    
        private int _lastSyncPulseTime;
    
        private double _photodiodeValue;
    
        private int _last2PFrameTime;
    
        private int _last2PLineTime;
    
        private int _currentMillis;
    
        public MatrixArduinoData()
        {
        }
    
        protected MatrixArduinoData(MatrixArduinoData other)
        {
            _encoderPos = other._encoderPos;
            _lastLeftLickTime = other._lastLeftLickTime;
            _lastRightLickTime = other._lastRightLickTime;
            _lastSyncPulseTime = other._lastSyncPulseTime;
            _photodiodeValue = other._photodiodeValue;
            _last2PFrameTime = other._last2PFrameTime;
            _last2PLineTime = other._last2PLineTime;
            _currentMillis = other._currentMillis;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("encoderPos", Required=Newtonsoft.Json.Required.Always)]
        public int EncoderPos
        {
            get
            {
                return _encoderPos;
            }
            set
            {
                _encoderPos = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("lastLeftLickTime", Required=Newtonsoft.Json.Required.Always)]
        public int LastLeftLickTime
        {
            get
            {
                return _lastLeftLickTime;
            }
            set
            {
                _lastLeftLickTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("lastRightLickTime", Required=Newtonsoft.Json.Required.Always)]
        public int LastRightLickTime
        {
            get
            {
                return _lastRightLickTime;
            }
            set
            {
                _lastRightLickTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("lastSyncPulseTime", Required=Newtonsoft.Json.Required.Always)]
        public int LastSyncPulseTime
        {
            get
            {
                return _lastSyncPulseTime;
            }
            set
            {
                _lastSyncPulseTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("photodiodeValue", Required=Newtonsoft.Json.Required.Always)]
        public double PhotodiodeValue
        {
            get
            {
                return _photodiodeValue;
            }
            set
            {
                _photodiodeValue = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("last2PFrameTime", Required=Newtonsoft.Json.Required.Always)]
        public int Last2PFrameTime
        {
            get
            {
                return _last2PFrameTime;
            }
            set
            {
                _last2PFrameTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("last2PLineTime", Required=Newtonsoft.Json.Required.Always)]
        public int Last2PLineTime
        {
            get
            {
                return _last2PLineTime;
            }
            set
            {
                _last2PLineTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("currentMillis", Required=Newtonsoft.Json.Required.Always)]
        public int CurrentMillis
        {
            get
            {
                return _currentMillis;
            }
            set
            {
                _currentMillis = value;
            }
        }
    
        public System.IObservable<MatrixArduinoData> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new MatrixArduinoData(this)));
        }
    
        public System.IObservable<MatrixArduinoData> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new MatrixArduinoData(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("EncoderPos = " + _encoderPos + ", ");
            stringBuilder.Append("LastLeftLickTime = " + _lastLeftLickTime + ", ");
            stringBuilder.Append("LastRightLickTime = " + _lastRightLickTime + ", ");
            stringBuilder.Append("LastSyncPulseTime = " + _lastSyncPulseTime + ", ");
            stringBuilder.Append("PhotodiodeValue = " + _photodiodeValue + ", ");
            stringBuilder.Append("Last2PFrameTime = " + _last2PFrameTime + ", ");
            stringBuilder.Append("Last2PLineTime = " + _last2PLineTime + ", ");
            stringBuilder.Append("CurrentMillis = " + _currentMillis);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Screen
    {
    
        private string _deviceType;
    
        private int _displayIndex;
    
        private double _targetRenderFrequency;
    
        private double _targetUpdateFrequency;
    
        private string _textureAssetsDirectory;
    
        private System.Collections.Generic.Dictionary<string, DisplayCalibration> _calibration;
    
        private double _brightness;
    
        private double _contrast;
    
        public Screen()
        {
            _deviceType = "Screen";
            _displayIndex = 1;
            _targetRenderFrequency = 60D;
            _targetUpdateFrequency = 120D;
            _textureAssetsDirectory = "Textures";
            _brightness = 0D;
            _contrast = 1D;
        }
    
        protected Screen(Screen other)
        {
            _deviceType = other._deviceType;
            _displayIndex = other._displayIndex;
            _targetRenderFrequency = other._targetRenderFrequency;
            _targetUpdateFrequency = other._targetUpdateFrequency;
            _textureAssetsDirectory = other._textureAssetsDirectory;
            _calibration = other._calibration;
            _brightness = other._brightness;
            _contrast = other._contrast;
        }
    
        /// <summary>
        /// Device type
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("deviceType")]
        [System.ComponentModel.DescriptionAttribute("Device type")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// Display index
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayIndex")]
        [System.ComponentModel.DescriptionAttribute("Display index")]
        public int DisplayIndex
        {
            get
            {
                return _displayIndex;
            }
            set
            {
                _displayIndex = value;
            }
        }
    
        /// <summary>
        /// Target render frequency
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("targetRenderFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target render frequency")]
        public double TargetRenderFrequency
        {
            get
            {
                return _targetRenderFrequency;
            }
            set
            {
                _targetRenderFrequency = value;
            }
        }
    
        /// <summary>
        /// Target update frequency
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("targetUpdateFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target update frequency")]
        public double TargetUpdateFrequency
        {
            get
            {
                return _targetUpdateFrequency;
            }
            set
            {
                _targetUpdateFrequency = value;
            }
        }
    
        /// <summary>
        /// Calibration directory
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("textureAssetsDirectory")]
        [System.ComponentModel.DescriptionAttribute("Calibration directory")]
        public string TextureAssetsDirectory
        {
            get
            {
                return _textureAssetsDirectory;
            }
            set
            {
                _textureAssetsDirectory = value;
            }
        }
    
        /// <summary>
        /// Calibration parameters for a set of named display monitors for visual stimuli
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("calibration")]
        [System.ComponentModel.DescriptionAttribute("Calibration parameters for a set of named display monitors for visual stimuli")]
        public System.Collections.Generic.Dictionary<string, DisplayCalibration> Calibration
        {
            get
            {
                return _calibration;
            }
            set
            {
                _calibration = value;
            }
        }
    
        /// <summary>
        /// Brightness
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("brightness")]
        [System.ComponentModel.DescriptionAttribute("Brightness")]
        public double Brightness
        {
            get
            {
                return _brightness;
            }
            set
            {
                _brightness = value;
            }
        }
    
        /// <summary>
        /// Contrast
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("contrast")]
        [System.ComponentModel.DescriptionAttribute("Contrast")]
        public double Contrast
        {
            get
            {
                return _contrast;
            }
            set
            {
                _contrast = value;
            }
        }
    
        public System.IObservable<Screen> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Screen(this)));
        }
    
        public System.IObservable<Screen> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Screen(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("DisplayIndex = " + _displayIndex + ", ");
            stringBuilder.Append("TargetRenderFrequency = " + _targetRenderFrequency + ", ");
            stringBuilder.Append("TargetUpdateFrequency = " + _targetUpdateFrequency + ", ");
            stringBuilder.Append("TextureAssetsDirectory = " + _textureAssetsDirectory + ", ");
            stringBuilder.Append("Calibration = " + _calibration + ", ");
            stringBuilder.Append("Brightness = " + _brightness + ", ");
            stringBuilder.Append("Contrast = " + _contrast);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SyncQuad
    {
    
        private double _extentX;
    
        private double _extentY;
    
        private double _locationX;
    
        private double _locationY;
    
        public SyncQuad()
        {
        }
    
        protected SyncQuad(SyncQuad other)
        {
            _extentX = other._extentX;
            _extentY = other._extentY;
            _locationX = other._locationX;
            _locationY = other._locationY;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("extentX", Required=Newtonsoft.Json.Required.Always)]
        public double ExtentX
        {
            get
            {
                return _extentX;
            }
            set
            {
                _extentX = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("extentY", Required=Newtonsoft.Json.Required.Always)]
        public double ExtentY
        {
            get
            {
                return _extentY;
            }
            set
            {
                _extentY = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("locationX", Required=Newtonsoft.Json.Required.Always)]
        public double LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("locationY", Required=Newtonsoft.Json.Required.Always)]
        public double LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
    
        public System.IObservable<SyncQuad> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SyncQuad(this)));
        }
    
        public System.IObservable<SyncQuad> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SyncQuad(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ExtentX = " + _extentX + ", ");
            stringBuilder.Append("ExtentY = " + _extentY + ", ");
            stringBuilder.Append("LocationX = " + _locationX + ", ");
            stringBuilder.Append("LocationY = " + _locationY);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Trial
    {
    
        private System.Collections.Generic.List<System.Collections.Generic.List<Landmark>> _landmarks;
    
        private Landmark _backgroundLandmarkLeft;
    
        private Landmark _backgroundLandmarkRight;
    
        private Landmark _backgroundLandmarkCeil;
    
        private Landmark _backgroundLandmarkFloor;
    
        private double _boundaryThreshold;
    
        private double _endTrialThreshold;
    
        private double _maximumTrialTime;
    
        private double _interTrialIntervalLowerBound;
    
        private double _interTrialIntervalUpperBound;
    
        private double _detectLickThreshold;
    
        private double _autoRewardThreshold;
    
        private double _movementVisualGain;
    
        public Trial()
        {
            _landmarks = new System.Collections.Generic.List<System.Collections.Generic.List<Landmark>>();
            _backgroundLandmarkLeft = new Landmark();
            _backgroundLandmarkRight = new Landmark();
            _backgroundLandmarkCeil = new Landmark();
            _backgroundLandmarkFloor = new Landmark();
            _boundaryThreshold = 1D;
            _endTrialThreshold = 1.5D;
            _maximumTrialTime = 60D;
            _interTrialIntervalLowerBound = 1D;
            _interTrialIntervalUpperBound = 3D;
            _detectLickThreshold = -1D;
            _autoRewardThreshold = 10D;
            _movementVisualGain = 0.0613D;
        }
    
        protected Trial(Trial other)
        {
            _landmarks = other._landmarks;
            _backgroundLandmarkLeft = other._backgroundLandmarkLeft;
            _backgroundLandmarkRight = other._backgroundLandmarkRight;
            _backgroundLandmarkCeil = other._backgroundLandmarkCeil;
            _backgroundLandmarkFloor = other._backgroundLandmarkFloor;
            _boundaryThreshold = other._boundaryThreshold;
            _endTrialThreshold = other._endTrialThreshold;
            _maximumTrialTime = other._maximumTrialTime;
            _interTrialIntervalLowerBound = other._interTrialIntervalLowerBound;
            _interTrialIntervalUpperBound = other._interTrialIntervalUpperBound;
            _detectLickThreshold = other._detectLickThreshold;
            _autoRewardThreshold = other._autoRewardThreshold;
            _movementVisualGain = other._movementVisualGain;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("landmarks", Required=Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.List<System.Collections.Generic.List<Landmark>> Landmarks
        {
            get
            {
                return _landmarks;
            }
            set
            {
                _landmarks = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("backgroundLandmarkLeft", Required=Newtonsoft.Json.Required.Always)]
        public Landmark BackgroundLandmarkLeft
        {
            get
            {
                return _backgroundLandmarkLeft;
            }
            set
            {
                _backgroundLandmarkLeft = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("backgroundLandmarkRight", Required=Newtonsoft.Json.Required.Always)]
        public Landmark BackgroundLandmarkRight
        {
            get
            {
                return _backgroundLandmarkRight;
            }
            set
            {
                _backgroundLandmarkRight = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("backgroundLandmarkCeil", Required=Newtonsoft.Json.Required.Always)]
        public Landmark BackgroundLandmarkCeil
        {
            get
            {
                return _backgroundLandmarkCeil;
            }
            set
            {
                _backgroundLandmarkCeil = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("backgroundLandmarkFloor", Required=Newtonsoft.Json.Required.Always)]
        public Landmark BackgroundLandmarkFloor
        {
            get
            {
                return _backgroundLandmarkFloor;
            }
            set
            {
                _backgroundLandmarkFloor = value;
            }
        }
    
        /// <summary>
        /// Buffer applied to far boundary of corridor to determine stopping distance.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("boundaryThreshold")]
        [System.ComponentModel.DescriptionAttribute("Buffer applied to far boundary of corridor to determine stopping distance.")]
        public double BoundaryThreshold
        {
            get
            {
                return _boundaryThreshold;
            }
            set
            {
                _boundaryThreshold = value;
            }
        }
    
        /// <summary>
        /// Buffer applied to far boundary of corridor to determine trial end distance.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("endTrialThreshold")]
        [System.ComponentModel.DescriptionAttribute("Buffer applied to far boundary of corridor to determine trial end distance.")]
        public double EndTrialThreshold
        {
            get
            {
                return _endTrialThreshold;
            }
            set
            {
                _endTrialThreshold = value;
            }
        }
    
        /// <summary>
        /// Maximum amount of time to spend on this trial.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("maximumTrialTime")]
        [System.ComponentModel.DescriptionAttribute("Maximum amount of time to spend on this trial.")]
        public double MaximumTrialTime
        {
            get
            {
                return _maximumTrialTime;
            }
            set
            {
                _maximumTrialTime = value;
            }
        }
    
        /// <summary>
        /// After boundary is reached, how long to wait before proceeding to next trial (lower bound).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("interTrialIntervalLowerBound")]
        [System.ComponentModel.DescriptionAttribute("After boundary is reached, how long to wait before proceeding to next trial (lowe" +
            "r bound).")]
        public double InterTrialIntervalLowerBound
        {
            get
            {
                return _interTrialIntervalLowerBound;
            }
            set
            {
                _interTrialIntervalLowerBound = value;
            }
        }
    
        /// <summary>
        /// After boundary is reached, how long to wait before proceeding to next trial (upper bound).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("interTrialIntervalUpperBound")]
        [System.ComponentModel.DescriptionAttribute("After boundary is reached, how long to wait before proceeding to next trial (uppe" +
            "r bound).")]
        public double InterTrialIntervalUpperBound
        {
            get
            {
                return _interTrialIntervalUpperBound;
            }
            set
            {
                _interTrialIntervalUpperBound = value;
            }
        }
    
        /// <summary>
        /// Threshold after which licks are detected.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("detectLickThreshold")]
        [System.ComponentModel.DescriptionAttribute("Threshold after which licks are detected.")]
        public double DetectLickThreshold
        {
            get
            {
                return _detectLickThreshold;
            }
            set
            {
                _detectLickThreshold = value;
            }
        }
    
        /// <summary>
        /// Reward is automatically given after this threshold is reached.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("autoRewardThreshold")]
        [System.ComponentModel.DescriptionAttribute("Reward is automatically given after this threshold is reached.")]
        public double AutoRewardThreshold
        {
            get
            {
                return _autoRewardThreshold;
            }
            set
            {
                _autoRewardThreshold = value;
            }
        }
    
        /// <summary>
        /// Gain between encoder delta and visual movement.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("movementVisualGain")]
        [System.ComponentModel.DescriptionAttribute("Gain between encoder delta and visual movement.")]
        public double MovementVisualGain
        {
            get
            {
                return _movementVisualGain;
            }
            set
            {
                _movementVisualGain = value;
            }
        }
    
        public System.IObservable<Trial> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Trial(this)));
        }
    
        public System.IObservable<Trial> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Trial(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Landmarks = " + _landmarks + ", ");
            stringBuilder.Append("BackgroundLandmarkLeft = " + _backgroundLandmarkLeft + ", ");
            stringBuilder.Append("BackgroundLandmarkRight = " + _backgroundLandmarkRight + ", ");
            stringBuilder.Append("BackgroundLandmarkCeil = " + _backgroundLandmarkCeil + ", ");
            stringBuilder.Append("BackgroundLandmarkFloor = " + _backgroundLandmarkFloor + ", ");
            stringBuilder.Append("BoundaryThreshold = " + _boundaryThreshold + ", ");
            stringBuilder.Append("EndTrialThreshold = " + _endTrialThreshold + ", ");
            stringBuilder.Append("MaximumTrialTime = " + _maximumTrialTime + ", ");
            stringBuilder.Append("InterTrialIntervalLowerBound = " + _interTrialIntervalLowerBound + ", ");
            stringBuilder.Append("InterTrialIntervalUpperBound = " + _interTrialIntervalUpperBound + ", ");
            stringBuilder.Append("DetectLickThreshold = " + _detectLickThreshold + ", ");
            stringBuilder.Append("AutoRewardThreshold = " + _autoRewardThreshold + ", ");
            stringBuilder.Append("MovementVisualGain = " + _movementVisualGain);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenSession
    {
    
        private string _workflow;
    
        private string _commit;
    
        private string _repositoryUrl;
    
        private string _loggingRootPath;
    
        private string _animalId;
    
        private string _sessionId;
    
        public UclOpenSession()
        {
        }
    
        protected UclOpenSession(UclOpenSession other)
        {
            _workflow = other._workflow;
            _commit = other._commit;
            _repositoryUrl = other._repositoryUrl;
            _loggingRootPath = other._loggingRootPath;
            _animalId = other._animalId;
            _sessionId = other._sessionId;
        }
    
        /// <summary>
        /// Path to the workflow running the experiment.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("workflow", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Path to the workflow running the experiment.")]
        public string Workflow
        {
            get
            {
                return _workflow;
            }
            set
            {
                _workflow = value;
            }
        }
    
        /// <summary>
        /// Commit hash of the experiment/rig repo.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("commit", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Commit hash of the experiment/rig repo.")]
        public string Commit
        {
            get
            {
                return _commit;
            }
            set
            {
                _commit = value;
            }
        }
    
        /// <summary>
        /// The URL of the git repository used to version experiment source code.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("repositoryUrl", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The URL of the git repository used to version experiment source code.")]
        public string RepositoryUrl
        {
            get
            {
                return _repositoryUrl;
            }
            set
            {
                _repositoryUrl = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("loggingRootPath", Required=Newtonsoft.Json.Required.Always)]
        public string LoggingRootPath
        {
            get
            {
                return _loggingRootPath;
            }
            set
            {
                _loggingRootPath = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("animalId", Required=Newtonsoft.Json.Required.Always)]
        public string AnimalId
        {
            get
            {
                return _animalId;
            }
            set
            {
                _animalId = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("sessionId", Required=Newtonsoft.Json.Required.Always)]
        public string SessionId
        {
            get
            {
                return _sessionId;
            }
            set
            {
                _sessionId = value;
            }
        }
    
        public System.IObservable<UclOpenSession> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenSession(this)));
        }
    
        public System.IObservable<UclOpenSession> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenSession(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Workflow = " + _workflow + ", ");
            stringBuilder.Append("Commit = " + _commit + ", ");
            stringBuilder.Append("RepositoryUrl = " + _repositoryUrl + ", ");
            stringBuilder.Append("LoggingRootPath = " + _loggingRootPath + ", ");
            stringBuilder.Append("AnimalId = " + _animalId + ", ");
            stringBuilder.Append("SessionId = " + _sessionId);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenVrCorridor2pRig
    {
    
        private string _version;
    
        private Screen _screen;
    
        private string _gammaCorrectionFile;
    
        private SyncQuad _syncQuad;
    
        private MatrixArduino _arduino;
    
        private double _quadTimeLowerBound;
    
        private double _quadTimeUpperBound;
    
        public UclOpenVrCorridor2pRig()
        {
            _version = "0.0.0-rc1";
            _screen = new Screen();
            _syncQuad = new SyncQuad();
            _arduino = new MatrixArduino();
            _quadTimeLowerBound = 0.2D;
            _quadTimeUpperBound = 0.5D;
        }
    
        protected UclOpenVrCorridor2pRig(UclOpenVrCorridor2pRig other)
        {
            _version = other._version;
            _screen = other._screen;
            _gammaCorrectionFile = other._gammaCorrectionFile;
            _syncQuad = other._syncQuad;
            _arduino = other._arduino;
            _quadTimeLowerBound = other._quadTimeLowerBound;
            _quadTimeUpperBound = other._quadTimeUpperBound;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("screen", Required=Newtonsoft.Json.Required.Always)]
        public Screen Screen
        {
            get
            {
                return _screen;
            }
            set
            {
                _screen = value;
            }
        }
    
        /// <summary>
        /// Path to file to be used as gamma LUT.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("gammaCorrectionFile", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Path to file to be used as gamma LUT.")]
        public string GammaCorrectionFile
        {
            get
            {
                return _gammaCorrectionFile;
            }
            set
            {
                _gammaCorrectionFile = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("syncQuad", Required=Newtonsoft.Json.Required.Always)]
        public SyncQuad SyncQuad
        {
            get
            {
                return _syncQuad;
            }
            set
            {
                _syncQuad = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("arduino", Required=Newtonsoft.Json.Required.Always)]
        public MatrixArduino Arduino
        {
            get
            {
                return _arduino;
            }
            set
            {
                _arduino = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("quadTimeLowerBound")]
        public double QuadTimeLowerBound
        {
            get
            {
                return _quadTimeLowerBound;
            }
            set
            {
                _quadTimeLowerBound = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("quadTimeUpperBound")]
        public double QuadTimeUpperBound
        {
            get
            {
                return _quadTimeUpperBound;
            }
            set
            {
                _quadTimeUpperBound = value;
            }
        }
    
        public System.IObservable<UclOpenVrCorridor2pRig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenVrCorridor2pRig(this)));
        }
    
        public System.IObservable<UclOpenVrCorridor2pRig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenVrCorridor2pRig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Screen = " + _screen + ", ");
            stringBuilder.Append("GammaCorrectionFile = " + _gammaCorrectionFile + ", ");
            stringBuilder.Append("SyncQuad = " + _syncQuad + ", ");
            stringBuilder.Append("Arduino = " + _arduino + ", ");
            stringBuilder.Append("QuadTimeLowerBound = " + _quadTimeLowerBound + ", ");
            stringBuilder.Append("QuadTimeUpperBound = " + _quadTimeUpperBound);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenVrCorridor2pTaskLogic
    {
    
        private string _version;
    
        private string _name;
    
        private UclOpenVrCorridor2pTaskParameters _taskParameters;
    
        public UclOpenVrCorridor2pTaskLogic()
        {
            _version = "0.0.0-rc1";
            _name = "UclOpenVrCorridor2p";
            _taskParameters = new UclOpenVrCorridor2pTaskParameters();
        }
    
        protected UclOpenVrCorridor2pTaskLogic(UclOpenVrCorridor2pTaskLogic other)
        {
            _version = other._version;
            _name = other._name;
            _taskParameters = other._taskParameters;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        /// <summary>
        /// Name of the task logic
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        [System.ComponentModel.DescriptionAttribute("Name of the task logic")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        /// <summary>
        /// Parameters of the task logic
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("taskParameters", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Parameters of the task logic")]
        public UclOpenVrCorridor2pTaskParameters TaskParameters
        {
            get
            {
                return _taskParameters;
            }
            set
            {
                _taskParameters = value;
            }
        }
    
        public System.IObservable<UclOpenVrCorridor2pTaskLogic> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenVrCorridor2pTaskLogic(this)));
        }
    
        public System.IObservable<UclOpenVrCorridor2pTaskLogic> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenVrCorridor2pTaskLogic(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("TaskParameters = " + _taskParameters);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenVrCorridor2pTaskParameters
    {
    
        private double _corridorWidth;
    
        private double _farClip;
    
        private System.Collections.Generic.List<Block> _blocks;
    
        public UclOpenVrCorridor2pTaskParameters()
        {
            _corridorWidth = 2D;
            _farClip = 20D;
            _blocks = new System.Collections.Generic.List<Block>();
        }
    
        protected UclOpenVrCorridor2pTaskParameters(UclOpenVrCorridor2pTaskParameters other)
        {
            _corridorWidth = other._corridorWidth;
            _farClip = other._farClip;
            _blocks = other._blocks;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("corridorWidth")]
        public double CorridorWidth
        {
            get
            {
                return _corridorWidth;
            }
            set
            {
                _corridorWidth = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("farClip")]
        public double FarClip
        {
            get
            {
                return _farClip;
            }
            set
            {
                _farClip = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("blocks", Required=Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.List<Block> Blocks
        {
            get
            {
                return _blocks;
            }
            set
            {
                _blocks = value;
            }
        }
    
        public System.IObservable<UclOpenVrCorridor2pTaskParameters> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenVrCorridor2pTaskParameters(this)));
        }
    
        public System.IObservable<UclOpenVrCorridor2pTaskParameters> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenVrCorridor2pTaskParameters(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CorridorWidth = " + _corridorWidth + ", ");
            stringBuilder.Append("FarClip = " + _farClip + ", ");
            stringBuilder.Append("Blocks = " + _blocks);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Vector3
    {
    
        private double _x;
    
        private double _y;
    
        private double _z;
    
        public Vector3()
        {
        }
    
        protected Vector3(Vector3 other)
        {
            _x = other._x;
            _y = other._y;
            _z = other._z;
        }
    
        /// <summary>
        /// X coordinate of the point.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("x", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("X coordinate of the point.")]
        public double X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
    
        /// <summary>
        /// Y coordinate of the point.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("y", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Y coordinate of the point.")]
        public double Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    
        /// <summary>
        /// Z coordinate of the point.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("z", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Z coordinate of the point.")]
        public double Z
        {
            get
            {
                return _z;
            }
            set
            {
                _z = value;
            }
        }
    
        public System.IObservable<Vector3> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Vector3(this)));
        }
    
        public System.IObservable<Vector3> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Vector3(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("X = " + _x + ", ");
            stringBuilder.Append("Y = " + _y + ", ");
            stringBuilder.Append("Z = " + _z);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<Block> source)
        {
            return Process<Block>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayCalibration> source)
        {
            return Process<DisplayCalibration>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayExtrinsics> source)
        {
            return Process<DisplayExtrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayIntrinsics> source)
        {
            return Process<DisplayIntrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Landmark> source)
        {
            return Process<Landmark>(source);
        }

        public System.IObservable<string> Process(System.IObservable<MatrixArduino> source)
        {
            return Process<MatrixArduino>(source);
        }

        public System.IObservable<string> Process(System.IObservable<MatrixArduinoData> source)
        {
            return Process<MatrixArduinoData>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Screen> source)
        {
            return Process<Screen>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SyncQuad> source)
        {
            return Process<SyncQuad>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Trial> source)
        {
            return Process<Trial>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenSession> source)
        {
            return Process<UclOpenSession>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenVrCorridor2pRig> source)
        {
            return Process<UclOpenVrCorridor2pRig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenVrCorridor2pTaskLogic> source)
        {
            return Process<UclOpenVrCorridor2pTaskLogic>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenVrCorridor2pTaskParameters> source)
        {
            return Process<UclOpenVrCorridor2pTaskParameters>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Vector3> source)
        {
            return Process<Vector3>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Block>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayCalibration>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayExtrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayIntrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Landmark>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<MatrixArduino>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<MatrixArduinoData>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Screen>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SyncQuad>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Trial>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenSession>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenVrCorridor2pRig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenVrCorridor2pTaskLogic>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenVrCorridor2pTaskParameters>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Vector3>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<Block>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}